#!/bin/bash
sudo yum update -y
sudo setenforce 0
sudo systemctl stop firewall-cmd
sudo yum install -y vim nano git python38 
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install docker-ce docker-ce-cli containerd.io -y
sudo systemctl enable docker
sudo systemctl start docker
sudo groupadd docker
sudo usermod -aG docker paul
newgrp docker
sudo pip3 install docker-compose
sudo reboot