# tirer l'image docker de base tiré de dockerhub
FROM node:14.7-alpine3.12
# exposer le port 8080 
EXPOSE 3000
# spécifier chemin dans lequel les instructions suivantes seront exectutées
WORKDIR /app
# copier les fichier de l'application node dans /app/
COPY ./app /app/
# executer la commande npm install
RUN npm install
# lancer la commande "npm" 
ENTRYPOINT [ "npm" ]
# spécifier l'argument du entrypoint donc start de "npm start"
CMD [ "start" ]